#!/bin/bash
set -eu

PREFIX="$(cd ../../opt && pwd -P)"
cd "$(dirname "$0")/../portaudio"
cd "$(pwd -P)"
CC=clang ./configure --prefix="$PREFIX"
make clean
make
printf '# Installing portaudio.\n'
sudo make install
printf '# Installation completed.\n'
