#!/bin/bash
set -eu

INSTDIR="/Library/Frameworks"
# mkdir -p "${INSTDIR}"

cd "$(dirname "$0")/.."
cd "$(pwd -P)"

(
    cd midishare/src/macosx-mono
    rm -rf build/Deployment/MidiShare.framework
    xcodebuild -project 'midishare.xcodeproj'  -target 'midishare' -configuration 'Deployment'
    printf '# Installing the MidiShare framework.\n'
    sudo rm -rf "${INSTDIR}"/MidiShare.framework
    sudo cp -a build/Deployment/MidiShare.framework "${INSTDIR}"/MidiShare.framework
    printf '# Installation complete.\n'
)

(
    cd midishare/libraries/player/macosx
    rm -rf build/Deployment/Player.framework
    xcodebuild -project 'Player.xcodeproj' -target 'Player Universal' -configuration 'Deployment'
    printf '# Installing the Player framework.\n'
    sudo rm -rf "${INSTDIR}"/Player.framework
    sudo cp -a build/Deployment/Player.framework "${INSTDIR}"/Player.framework
    printf '# Installation complete.\n'
)
